# Generated by Django 3.2.9 on 2021-12-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperteam',
            name='group',
        ),
        migrations.DeleteModel(
            name='Helper',
        ),
        migrations.DeleteModel(
            name='HelperGroup',
        ),
        migrations.DeleteModel(
            name='HelperTeam',
        ),
    ]
